replicaCount: 1

image:
  repository: aamitv/demo
  tag: latest
  port: 8080

serviceAccount:
  create: true
  name: ""

service:
  type: NodePort
  port: 8080
  nodePort: 32000

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

env:
  javaOpts: "-Dapp.env=staging"
